# 문서 군집화 (Document Clustering)

- Opinion Review 데이터셋
    - 다양한 주제에 대한 텍스트 리뷰와 의견을 모은 데이터셋
    - https://archive.ics.uci.edu/dataset/191/opinosis+opinion+frasl+review

**데이터셋 구조**

```
OpinosisDataset1.0/
│
├── OpinosisDataset1.1.pdf         # 데이터셋 설명서
│
├── examples/                      # 예제 폴더
│   └─── prepare4rouge/            # 텍스트 요약 평가를 위한 준비 폴더
│       ├── input/                 # 입력 데이터 폴더
│       └── output/                # Rouge 평가 결과 폴더
│
├── scripts/                       # 스크립트 파일 폴더
├── summaries-gold/                # 골드 요약 데이터 모음
└── topics/                        # 주제별 원본 데이터 폴더
    ├── accuracy_garmin_nuvi_255W_gps.txt.data   # Garmin Nuvi 255W GPS의 정확성에 대한 의견
    ├── bathroom_bestwestern_hotel_sfo.txt.data  # Best Western Hotel (San Francisco)의 화장실 관련 의견
    ├── battery-life_amazon_kindle.txt.data      # Amazon Kindle의 배터리 수명에 대한 의견
    ├── battery-life_ipod_nano_8gb.txt.data      # iPod Nano 8GB의 배터리 수명에 대한 의견
    ├── battery-life_netbook_1005ha.txt.data     # ASUS Netbook 1005HA의 배터리 수명에 대한 의견
    ├── buttons_amazon_kindle.txt.data           # Amazon Kindle의 버튼에 대한 의견
    ├── comfort_honda_accord_2008.txt.data       # 2008년형 Honda Accord의 편안함에 대한 의견
    ├── comfort_toyota_camry_2007.txt.data       # 2007년형 Toyota Camry의 편안함에 대한 의견
    ├── directions_garmin_nuvi_255W_gps.txt.data # Garmin Nuvi 255W GPS의 길 안내 성능에 대한 의견
    ├── display_garmin_nuvi_255W_gps.txt.data    # Garmin Nuvi 255W GPS의 디스플레이 성능에 대한 의견
    ├── eyesight-issues_amazon_kindle.txt.data   # Amazon Kindle 사용 중 시력 관련 문제에 대한 의견
    ├── features_windows7.txt.data               # Windows 7의 기능에 대한 의견
    ├── fonts_amazon_kindle.txt.data             # Amazon Kindle의 폰트에 대한 의견
    ├── food_holiday_inn_london.txt.data         # Holiday Inn (London)의 음식에 대한 의견
    ├── food_swissotel_chicago.txt.data          # Swissotel (Chicago)의 음식에 대한 의견
    ├── free_bestwestern_hotel_sfo.txt.data      # Best Western Hotel (San Francisco) 무료 서비스에 대한 의견
    ├── gas_mileage_toyota_camry_2007.txt.data   # 2007년형 Toyota Camry의 연비에 대한 의견
    ├── interior_honda_accord_2008.txt.data      # 2008년형 Honda Accord의 실내 디자인에 대한 의견
    ├── interior_toyota_camry_2007.txt.data      # 2007년형 Toyota Camry의 실내 디자인에 대한 의견
    ├── keyboard_netbook_1005ha.txt.data         # ASUS Netbook 1005HA의 키보드에 대한 의견
    ├── location_bestwestern_hotel_sfo.txt.data  # Best Western Hotel (San Francisco)의 위치에 대한 의견
    ├── location_holiday_inn_london.txt.data     # Holiday Inn (London)의 위치에 대한 의견
    ├── mileage_honda_accord_2008.txt.data       # 2008년형 Honda Accord의 연비에 대한 의견
    ├── navigation_amazon_kindle.txt.data        # Amazon Kindle의 탐색 성능에 대한 의견
    ├── parking_bestwestern_hotel_sfo.txt.data   # Best Western Hotel (San Francisco)의 주차장에 대한 의견
    ├── performance_honda_accord_2008.txt.data   # 2008년형 Honda Accord의 성능에 대한 의견
    ├── performance_netbook_1005ha.txt.data      # ASUS Netbook 1005HA의 성능에 대한 의견
    ├── price_amazon_kindle.txt.data             # Amazon Kindle의 가격에 대한 의견
    ├── price_holiday_inn_london.txt.data        # Holiday Inn (London)의 가격에 대한 의견
    ├── quality_toyota_camry_2007.txt.data       # 2007년형 Toyota Camry의 품질에 대한 의견
    ├── room_holiday_inn_london.txt.data         # Holiday Inn (London)의 객실에 대한 의견
    ├── rooms_bestwestern_hotel_sfo.txt.data     # Best Western Hotel (San Francisco)의 객실에 대한 의견
    ├── rooms_swissotel_chicago.txt.data         # Swissotel (Chicago)의 객실에 대한 의견
    ├── satellite_garmin_nuvi_255W_gps.txt.data  # Garmin Nuvi 255W GPS의 위성 연결 성능에 대한 의견
    ├── screen_garmin_nuvi_255W_gps.txt.data     # Garmin Nuvi 255W GPS의 화면에 대한 의견
    ├── screen_ipod_nano_8gb.txt.data            # iPod Nano 8GB의 화면 성능에 대한 의견
    ├── screen_netbook_1005ha.txt.data           # ASUS Netbook 1005HA의 화면 성능에 대한 의견
    ├── seats_honda_accord_2008.txt.data         # 2008년형 Honda Accord의 좌석에 대한 의견
    ├── service_bestwestern_hotel_sfo.txt.data   # Best Western Hotel (San Francisco)의 서비스에 대한 의견
    ├── service_holiday_inn_london.txt.data      # Holiday Inn (London)의 서비스에 대한 의견
    ├── service_swissotel_hotel_chicago.txt.data # Swissotel (Chicago)의 서비스에 대한 의견
    ├── size_asus_netbook_1005ha.txt.data        # ASUS Netbook 1005HA의 크기에 대한 의견
    ├── sound_ipod_nano_8gb.txt.data             # iPod Nano 8GB의 사운드 성능에 대한 의견
    ├── speed_garmin_nuvi_255W_gps.txt.data      # Garmin Nuvi 255W GPS의 속도에 대한 의견
    ├── speed_windows7.txt.data                  # Windows 7의 속도에 대한 의견
    ├── staff_bestwestern_hotel_sfo.txt.data     # Best Western Hotel (San Francisco)의 직원 서비스에 대한 의견
    ├── staff_swissotel_chicago.txt.data         # Swissotel (Chicago)의 직원 서비스에 대한 의견
    ├── transmission_toyota_camry_2007.txt.data  # 2007년형 Toyota Camry의 변속기에 대한 의견
    ├── updates_garmin_nuvi_255W_gps.txt.data    # Garmin Nuvi 255W GPS의 업데이트에 대한 의견
    ├── video_ipod_nano_8gb.txt.data             # iPod Nano 8GB의 비디오 성능에 대한 의견
    └── voice_garmin_nuvi_255W_gps.txt.data      # Garmin Nuvi 255W GPS의 음성 안내 성능에 대한 의견
```

In [2]:
import numpy as np
import pandas as pd
import os, glob

path = './data/OpinosisDataset1.0/topics'
all_files = glob.glob(os.path.join(path, '*.data'))

filename_list = []  # 파일명
opinions_list = []  # 파일 내용(의견)

for file_ in all_files:
    df = pd.read_table(
        file_,              # 경로
        header= None,       # 첫 줄은 컬럼명으로 사용안함
        index_col= None,    # 인덱스 컬럼 지정 안함(기본)
        encoding= 'latin1'  # 특수문자 깨짐방지
    )
    # display(df)
    
    filename = os.path.basename(file_)  # 파일명 추출
    filename = filename.split('.')[0]   # 확장자 제거
    filename_list.append(filename)      # 파일명 리스트 추가
    
    opinions = df.to_string(index=False, header=False) # 인덱스/ 헤더 제거
    opinions_list.append(opinions)

In [3]:
document_df = pd.DataFrame({
    'filename' : filename_list,
    'opinions' : opinions_list
})

document_df

,filename,opinions
0,accuracy_garmin_nuvi_255W_gps,...
1,bathroom_bestwestern_hotel_sfo,...
2,battery-life_amazon_kindle,...
3,battery-life_ipod_nano_8gb,...
4,battery-life_netbook_1005ha,...
5,buttons_amazon_kindle,...
6,comfort_honda_accord_2008,...
7,comfort_toyota_camry_2007,...
8,directions_garmin_nuvi_255W_gps,...
9,display_garmin_nuvi_255W_gps,...
10,eyesight-issues_amazon_kindle,...
11,features_windows7,...
12,fonts_amazon_kindle,...
13,food_holiday_inn_london,...
14,food_swissotel_chicago,...
15,free_bestwestern_hotel_sfo,...
16,gas_mileage_toyota_camry_2007,...
17,interior_honda_accord_2008,...
18,interior_toyota_camry_2007,...
19,keyboard_netbook_1005ha,...
20,location_bestwestern_hotel_sfo,...
21,location_holiday_inn_london,...
22,mileage_honda_accord_2008,...
23,navigation_amazon_kindle,...
24,parking_bestwestern_hotel_sfo,...
25,performance_honda_accord_2008,...
26,performance_netbook_1005ha,...
27,price_amazon_kindle,...
28,price_holiday_inn_london,...
29,quality_toyota_camry_2007,...
30,rooms_bestwestern_hotel_sfo,...
31,rooms_swissotel_chicago,...
32,room_holiday_inn_london,...
33,satellite_garmin_nuvi_255W_gps,...
34,screen_garmin_nuvi_255W_gps,...
35,screen_ipod_nano_8gb,...
36,screen_netbook_1005ha,...
37,seats_honda_accord_2008,...
38,service_bestwestern_hotel_sfo,...
39,service_holiday_inn_london,...
40,service_swissotel_hotel_chicago,...
41,size_asus_netbook_1005ha,...
42,sound_ipod_nano_8gb,headphone jack i got a clear case for it and ...
43,speed_garmin_nuvi_255W_gps,...
44,speed_windows7,...
45,staff_bestwestern_hotel_sfo,...
46,staff_swissotel_chicago,...
47,transmission_toyota_camry_2007,...
48,updates_garmin_nuvi_255W_gps,...
49,video_ipod_nano_8gb,...
50,voice_garmin_nuvi_255W_gps,...

### 특성 벡터화 및 전처리
- TfidfVectorizer 이용한 벡터화
- 불용어 처리
- ngram 설정
- 어근 분리(Lemmoatization)

In [ ]:
import nltk

nltk.download('wordnet')        # 대형 의미 사전

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\MoonSungHo\AppData\Roaming\nltk_data...

True

In [5]:
from nltk.stem import WordNetLemmatizer     # 표제어(lemma) 추출 도구

lemmatizer = WordNetLemmatizer()
print(lemmatizer.lemmatize('running', pos= 'v'))    # 동사로 간주해 표제어(사전 대표 기본형) 변환
print(lemmatizer.lemmatize('ran', pos= 'v'))

run
run

In [6]:
# 파이썬에서 사용하는 문장부호 목록
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
# 텍스트를 정리하고, 표제어(동사 기준)로 변환하는 함수
def lemmatizer(text):
    text = text.lower()     # 소문자 변환
    
    punc_rem_dict = dict((ord(ch), None) for ch in string.punctuation)  # 문장부포 제거용 치환 딕셔너리
    text = text.translate(punc_rem_dict)    # text 에서 문장부호에 해당하는 것들은 None 
    
    tokens = nltk.word_tokenize(text)
    
    lemmatizer = WordNetLemmatizer()
    return [lemmatizer.lemmatize(token, pos= 'v') for token in tokens]

lemmatizer('The Matrix is everywhere its all around us, here even in this room. \
You can see it out your window or on your television. \
You feel it when you go to work, or go to church or pay your taxes.')

['the',
 'matrix',
 'be',
 'everywhere',
 'its',
 'all',
 'around',
 'us',
 'here',
 'even',
 'in',
 'this',
 'room',
 'you',
 'can',
 'see',
 'it',
 'out',
 'your',
 'window',
 'or',
 'on',
 'your',
 'television',
 'you',
 'feel',
 'it',
 'when',
 'you',
 'go',
 'to',
 'work',
 'or',
 'go',
 'to',
 'church',
 'or',
 'pay',
 'your',
 'tax']

In [ ]:
# Lemmatize 적용한 후 TF-IDF 벡터화
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(
    tokenizer= lemmatizer,      # 사용자 정의 토크나이저 적용
    stop_words= 'english',      # 영어 불용어 제거
    ngram_range= (1,2),         # 유니그램, 
    max_df= 0.85,               # 전체 문서 85% 등장시 흔한 단어이므로 제외
    min_df= 0.05                # 전체 문서 5% 등장시 
)

opinions_vecs = tfidf_vectorizer.fit_transform(document_df['opinions'])
print(opinions_vecs.toarray().shape)    # 문서수, 특성 수 
print(opinions_vecs)                    # 희소행렬 출력

c:\Users\MoonSungHo\skn34-st\study\DL\DL_venv\Lib\site-packages\sklearn\feature_extraction\text.py:527: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\MoonSungHo\skn34-st\study\DL\DL_venv\Lib\site-packages\sklearn\feature_extraction\text.py:412: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['make'] not in stop_words.
  warnings.warn(

(51, 4072)
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 25383 stored elements and shape (51, 4072)>
  Coords	Values
  (0, 165)	0.7742542979210241
  (0, 1463)	0.07204716607359458
  (0, 3407)	0.016130297873354668
  (0, 2815)	0.03322048155310359
  (0, 1016)	0.1613798782436557
  (0, 1866)	0.020663607871398704
  (0, 1444)	0.013478481520354605
  (0, 1053)	0.007936997735176827
  (0, 2031)	0.01013758802410648
  (0, 360)	0.015122124086220925
  (0, 2358)	0.02934179604430104
  (0, 3165)	0.017183123909565296
  (0, 3550)	0.012166058278124673
  (0, 2226)	0.019655434084264962
  (0, 2686)	0.015122124086220925
  (0, 1459)	0.017322714375150577
  (0, 1799)	0.018011791518398646
  (0, 3143)	0.05196814312545173
  (0, 2540)	0.016699368276168712
  (0, 2266)	0.17743327660690134
  (0, 2803)	0.016699368276168712
  (0, 443)	0.015122124086220925
  (0, 1910)	0.04757120962562307
  (0, 1532)	0.2161414982207837
  (0, 3798)	0.017322714375150577
  :	:
  (50, 232)	0.012712026490235473
  (50, 2966)	0.012712026490235473
  (50, 773)	0.011266204213868735
  (50, 387)	0.012712026490235473
  (50, 1166)	0.012712026490235473
  (50, 3171)	0.012712026490235473
  (50, 303)	0.02383266614660507
  (50, 2827)	0.025424052980470947
  (50, 3801)	0.012712026490235473
  (50, 3442)	0.012712026490235473
  (50, 3184)	0.012712026490235473
  (50, 1167)	0.012712026490235473
  (50, 3042)	0.012712026490235473
  (50, 3910)	0.012712026490235473
  (50, 3808)	0.012712026490235473
  (50, 62)	0.012712026490235473
  (50, 3172)	0.012712026490235473
  (50, 3045)	0.025424052980470947
  (50, 3425)	0.025424052980470947
  (50, 3907)	0.012712026490235473
  (50, 891)	0.012712026490235473
  (50, 2169)	0.012712026490235473
  (50, 795)	0.012712026490235473
  (50, 2735)	0.012712026490235473
  (50, 1916)	0.012712026490235473

### KMeans 군집화

In [11]:
from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters= 4,
    max_iter= 5000,
    random_state= 0
)

opinions_label = kmeans.fit_predict(opinions_vecs)
document_df['cluster'] = opinions_label
document_df

,filename,opinions,cluster
0,accuracy_garmin_nuvi_255W_gps,...,2
1,bathroom_bestwestern_hotel_sfo,...,1
2,battery-life_amazon_kindle,...,0
3,battery-life_ipod_nano_8gb,...,2
4,battery-life_netbook_1005ha,...,2
5,buttons_amazon_kindle,...,0
6,comfort_honda_accord_2008,...,3
7,comfort_toyota_camry_2007,...,3
8,directions_garmin_nuvi_255W_gps,...,2
9,display_garmin_nuvi_255W_gps,...,2
10,eyesight-issues_amazon_kindle,...,0
11,features_windows7,...,2
12,fonts_amazon_kindle,...,0
13,food_holiday_inn_london,...,1
14,food_swissotel_chicago,...,1
15,free_bestwestern_hotel_sfo,...,1
16,gas_mileage_toyota_camry_2007,...,3
17,interior_honda_accord_2008,...,3
18,interior_toyota_camry_2007,...,3
19,keyboard_netbook_1005ha,...,2
20,location_bestwestern_hotel_sfo,...,1
21,location_holiday_inn_london,...,1
22,mileage_honda_accord_2008,...,3
23,navigation_amazon_kindle,...,0
24,parking_bestwestern_hotel_sfo,...,1
25,performance_honda_accord_2008,...,3
26,performance_netbook_1005ha,...,2
27,price_amazon_kindle,...,0
28,price_holiday_inn_london,...,0
29,quality_toyota_camry_2007,...,3
30,rooms_bestwestern_hotel_sfo,...,1
31,rooms_swissotel_chicago,...,1
32,room_holiday_inn_london,...,1
33,satellite_garmin_nuvi_255W_gps,...,2
34,screen_garmin_nuvi_255W_gps,...,2
35,screen_ipod_nano_8gb,...,2
36,screen_netbook_1005ha,...,2
37,seats_honda_accord_2008,...,3
38,service_bestwestern_hotel_sfo,...,1
39,service_holiday_inn_london,...,1
40,service_swissotel_hotel_chicago,...,1
41,size_asus_netbook_1005ha,...,2
42,sound_ipod_nano_8gb,headphone jack i got a clear case for it and ...,2
43,speed_garmin_nuvi_255W_gps,...,2
44,speed_windows7,...,0
45,staff_bestwestern_hotel_sfo,...,1
46,staff_swissotel_chicago,...,1
47,transmission_toyota_camry_2007,...,3
48,updates_garmin_nuvi_255W_gps,...,2
49,video_ipod_nano_8gb,...,2
50,voice_garmin_nuvi_255W_gps,...,2

In [16]:
# 클러스트 중신 키워드 (상위 TF-IDF ) 추출
centers = kmeans.cluster_centers_       # 각 클러스터별 중심 벡터
print(centers.shape)                    # (클러스터 수, 특성 수)

centroid_arg_idx = centers.argsort()[:, ::-1]   # 각 클러스터별 특성값 기준 내림차순하여, 인덱스 반환
top_20 = centroid_arg_idx[:, : 20]               # 클러스터별 상위 20개 특성 인덱스
feature_names = tfidf_vectorizer.get_feature_names_out()    # 이름
feature_names[top_20]       # 인덱스 -> 이름 매핑 출력

(4, 4072)

array([['kindle', 'price', 'page', 'button', 'font', 'battery', 'eye',
        'book', 'faster', 'navigation', 'font size', 'read', 'navigate',
        'easy', 'vista', 'screen', 'easy eye', 'kindle 2', 'hotel',
        'size'],
       ['room', 'service', 'hotel', 'staff', 'food', 'location', 'clean',
        'bathroom', 'park', 'room service', 'free', 'stay', 'friendly',
        'great location', 'wine', 'helpful', 'bed', 'breakfast', 'wharf',
        'tube'],
       ['screen', 'battery', 'keyboard', 'battery life', 'directions',
        'voice', 'map', 'life', 'video', 'feature', 'speed', 'display',
        'size', 'speed limit', 'accurate', 'satellite', 'update',
        'sound', 'performance', 'limit'],
       ['interior', 'seat', 'mileage', 'comfortable', 'gas',
        'gas mileage', 'transmission', 'car', 'performance', 'quality',
        'ride', 'comfort', 'camry', 'drive', 'toyota',
        'seat comfortable', 'accord', 'exterior', 'uncomfortable',
        'honda']], dtype=object)

### 코사인 유사도 (cosine similarity)
- 코사인 유사도(cosine similarity)는 두 벡터가 이루는 각도로 “얼마나 비슷한 방향을 보느냐”를 재는 지표
- 크기(길이)보다 방향에 집중해서, 문서 벡터(TF-IDF) 비교에 자주 사용한다.


 # 
- 값 범위(보통 TF-IDF처럼 음수가 없으면): 0 ~ 1
- 1: 거의 같은 방향(매우 유사)
- 0: 직교(공통 특징 거의 없음)
- (일반 벡터에서는 -1도 가능: 정반대 방향)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

doc_list = [
    'if you take the blue pill, the story ends',
    'if you take the blue pill, the stay in Wonderland',
    'if you take the blue pill, I show you how deep the rabbit hole goes',
]

tfidf_vectorizer = TfidfVectorizer()
doc_vects = tfidf_vectorizer.fit_transform(doc_list)    # 학습 + 문서 벡터화 (희소행렬)
print(doc_vects.shape)      # (문서 수, 단어 수)
print(sorted(tfidf_vectorizer.vocabulary_.items(), key = lambda x: x[1]))   # 단어사전은 인덱스 기준 정렬

doc_arr = doc_vects.toarray()       # 희소행렬 -> dense 배열 반환
cosine_similarity(doc_arr[2:], doc_arr) # 3번째 문서와 전체 문서 유사도

(3, 17)
[('blue', 0), ('deep', 1), ('ends', 2), ('goes', 3), ('hole', 4), ('how', 5), ('if', 6), ('in', 7), ('pill', 8), ('rabbit', 9), ('show', 10), ('stay', 11), ('story', 12), ('take', 13), ('the', 14), ('wonderland', 15), ('you', 16)]

array([[0.4821166 , 0.44110873, 1.        ]])